alternative_links:
  default: >-
    [{"category":"general","text":"New Secure Topic","url":"/faq", "icon": "lock"}]
  json_schema: '{ "type": "array", "format": "table", "uniqueItems": true, "items": { "type": "object", "properties": { "category": { "type": "string", "minLength": 1 }, "icon": { "type": "string" }, "text": { "type": "string", "minLength": 1 }, "url": { "type": "string" } }, "additionalProperties": false } }'